import turtle as t
t.begin_fill()
t.bgcolor("black")
t.color("white","yellow")
for i in range(1,10):
    t.begin_fill()
    t.color("pink")
    t.fd(100)
    t.right(150)
    t.fd(100)
    t.end_fill()
t.fd(100)
for i in range(1,10):
    t.begin_fill()
    t.color("orange")
    t.fd(100)
    t.right(150)
    t.fd(100)
    t.end_fill()
t.fd(100)
for i in range(1,10):
    t.begin_fill()
    t.color("green")
    t.fd(100)
    t.right(150)
    t.fd(100)
    t.end_fill()
t.fd(100)
for i in range(1,10):
    t.begin_fill()
    t.color("yellow")
    t.fd(100)
    t.right(150)
    t.fd(100)
    t.end_fill()
